# Copyright (C) 2025  A. Iooss
# SPDX-License-Identifier: CC0-1.0
apiVersion: 1

datasources:
  - name: Suricata Eve
    type: frser-sqlite-datasource
    jsonData:
      path: /suricata/output/eve.db
    isDefault: true
